//store a currency valuation for a specific time interval
export const ADD_CURRENCY_VALUATION = "ADD_CURRENCY_VALUATION"
export const REMOVE_CURRENCY_VALUATION = "REMOVE_CURRENCY_VALUATION"
export const TOGGLE_LOADING = "TOGGLE_LOADING_COINMARKETCAP"
export const SET_LAST_FETCH_UPDATE_COINS = "SET_LAST_FETCH_UPDATE_COINS"